import axios from "axios";
import {
  setError,
  setLoading,
  userLogin,
  userLogout,
  userSignup,
  setUserList,
  setShowUserList,
  setIsApproveAccount,
  setUpdateLoading,
  setUpdateError,
} from "../slices/user";

export const login = (email, password) => async (dispatch) => {
  dispatch(setLoading(true));
  try {
    const config = {
      headers: {
        "Content-Type": "application/json",
      },
    };
    const { data } = await axios.post(
      `${import.meta.env.VITE_BASE_URL}/api/users/login`,
      { email, password },
      config
    );

    dispatch(userLogin(data));
    console.log("Ä‘Äƒng nháº­p");
    localStorage.setItem("userInfo", JSON.stringify(data));
  } catch (error) {
    console.log("Lá»—i khi Ä‘Äƒng nháº­p");
    dispatch(
      setError(
        error.response && error.response.data.message
          ? error.response.data.message
          : error.message
          ? error.message
          : "An unexpected error has occured. Please try again later."
      )
    );
  }
};

export const getUserAccountList = () => async (dispatch, getState) => {
  dispatch(setLoading(true));
  const {
    user: { userInfo },
  } = getState();
  try {
    const config = {
      headers: {
        Authorization: `Bearer ${userInfo.accessToken}`,
        "Content-Type": "application/json",
      },
    };
    const { data } = await axios.get(
      `${import.meta.env.VITE_BASE_URL}/api/users`,
      config
    );
    const { users } = data;
    dispatch(setShowUserList(users));
    dispatch(setUserList(users));
    console.log("láº¥y ds user account");
  } catch (error) {
    dispatch(
      setError(
        error.response && error.response.data.message
          ? error.response.data.message
          : error.message
          ? error.message
          : "An unexpected error has occured. Please try again later."
      )
    );
  }
};

export const approveUserAccount = (id) => async (dispatch, getState) => {
  dispatch(setIsApproveAccount(false));
  const {
    user: { userInfo },
  } = getState();
  try {
    console.log(userInfo);
    const config = {
      headers: {
        Authorization: `Bearer ${userInfo.accessToken}`,
        "Content-Type": "application/json",
      },
    };
    const { data } = await axios.patch(
      `${import.meta.env.VITE_BASE_URL}/api/users/${id}/approve`,
      {},
      config
    );
    dispatch(setIsApproveAccount(true));
    console.log("xÃ¡c thá»±c account");
  } catch (error) {
    dispatch(
      setError(
        error.response && error.response.data.message
          ? error.response.data.message
          : error.message
          ? error.message
          : "An unexpected error has occured. Please try again later."
      )
    );
    dispatch(setIsApproveAccount(false));
  }
};

export const signup = (newUser) => async (dispatch) => {
  dispatch(setLoading(true));
  try {
    const config = {
      headers: {
        "Content-Type": "application/json",
      },
    };
    const { data } = await axios.post(
      `${import.meta.env.VITE_BASE_URL}/api/users/register`,
      newUser,
      config
    );

    dispatch(userSignup(data));
    console.log("Ä‘Äƒng kÃ½");
  } catch (error) {
    dispatch(
      setError(
        error.response && error.response.data.message
          ? error.response.data.message
          : error.message
          ? error.message
          : "An unexpected error has occured. Please try again later."
      )
    );
  }
};

export const logout = () => async (dispatch) => {
  localStorage.removeItem("userInfo");
  dispatch(userLogout());
};

export const updateProfile = (newInfo) => async (dispatch, getState) => {
  dispatch(setUpdateLoading(true));
  const {
    user: { userInfo },
  } = getState();
  try {
    const config = {
      headers: {
        Authorization: `Bearer ${userInfo.accessToken}`,
        "Content-Type": "application/json",
      },
    };
    const {
      user: { id },
    } = userInfo;
    const { data } = await axios.put(
      `${import.meta.env.VITE_BASE_URL}/api/users/${id}`,
      newInfo,
      config
    );
    console.log("ðŸš€ ~ update profile user:", data);
    dispatch(setUpdateLoading(false));
  } catch (error) {
    dispatch(
      setUpdateError(
        error.response && error.response.data.message
          ? error.response.data.message
          : error.message
          ? error.message
          : "An unexpected error has occured. Please try again later."
      )
    );
  }
};
